spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    filters: wall,stat
    max-active: 20
    initial-size: 5
    max-wait: 60000
    min-idle: 5
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 60000
    pool-prepared-statements: true
    max-open-prepared-statements: 20
#mybatis
mybatis:
  type-aliases-package: com.vankeytech.pmp.hms.entity
  mapper-locations: classpath:mapper/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.vankeytech.baseservice.mapper.BasicMapper
  not-empty: false
  identity: MYSQL

#可选连接
---
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

---
spring:
  profiles: test
  datasource:
    username: pmp_dev
    password: pmp2017@DEV
    url: jdbc:mysql://192.168.0.100:3306/pmp_hms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true