spring:
  profiles:
    active: dev   # 默认运行环境
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: wall,stat
      max-active: 20
      initial-size: 5
      max-wait: 60000
      min-idle: 5
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
dubbo:
  appname: pmp-ims-provider # dubbo应用名
  protocol:
    name: dubbo             # dubbo协议名，不用改
    port: 20889             # dubbo对外提供接口的端口号
    

#mybatis
mybatis:
  type-aliases-package: com.vankeytech.pmp.hms.entity
  mapper-locations: classpath:mapper/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.vankeytech.baseservice.mapper.BasicMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 开发环境
---
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
dubbo:
  debug: dubbo://localhost
  register: false
  registry: N/A

logging:
  level:
    com.vankeytech.pmp.common.mapper: debug

#测试环境
---
spring:
  profiles: test
  datasource:
    username: pmp_dev
    password: pmp2017@DEV
    url: jdbc:mysql://192.168.0.100:3306/pmp_hms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
dubbo:
  debug:
  register: true
  registry: 192.168.0.100:2181,192.168.0.101:2181