
server:
  port: 8002

spring:
  profiles:
    active: dev
  datasource:
    name: pmp_auth
    url : jdbc:mysql://192.168.0.100:3306/pmp_auth?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: pmp_dev
    password: pmp2017@DEV
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: wall,stat
    max-active: 20
    initial-size: 5
    max-wait: 60000
    min-idle: 5
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 60000
    pool-prepared-statements: true
    max-open-prepared-statements: 20
#mybatis
mybatis:
  type-aliases-package: com.vankeytech.pmp.auth.entity
  mapper-locations: classpath:mapper/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.vankeytech.baseservice.mapper.BasicMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

