spring:
  profiles:
    active: dev   # 默认运行环境
  datasource:
    name: pmp_auth
    url: jdbc:mysql://192.168.0.100:3306/pmp_common?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: pmp_dev
    password: pmp2017@DEV
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: wall,stat
    max-active: 20
    initial-size: 5
    max-wait: 60000
    min-idle: 5
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 60000
    pool-prepared-statements: true
    max-open-prepared-statements: 20

#mybatis
mybatis:
  type-aliases-package: com.vankeytech.pmp.common.entity
  mapper-locations: classpath:mapper/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.vankeytech.baseservice.mapper.BasicMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

dubbo:
  appname: pmp-common-provider # dubbo应用名
  protocol:
    name: dubbo             # dubbo协议名，不用改
    port: 20884             # dubbo对外提供接口的端口号

# 开发环境
---
spring:
  profiles: dev
dubbo:
  debug: dubbo://localhost
  register: false
  registry:
    - N/A
    - N/A
logging:
  level:
    com.vankeytech.pmp.common.mapper: debug

#测试环境
---
spring:
  profiles: test
dubbo:
  debug:
  register: true
  registry:
    - zookeeper://192.168.0.100:2181
    - zookeeper://192.168.0.101:2181