spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100:3306/pmp_cms?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: pmp_dev
    password: pmp2017@DEV
  redis:
    host: 192.168.0.100
    port: 6379
    password: vankey#2017
    database: 8
    pool:
      max-active: 1000
      maxWait: 5000
      maxIdle: 20
      min-idle: 0
    timeout: 0

dubbo:
  appname: pmp-cms-provider
  protocol:
    name: dubbo
    port: 20883

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.vankeytech.pmp.cms.entity

# 开发环境
---
spring:
  profiles: dev
dubbo:
  debug: dubbo://localhost
  register: false
  registry: N/A

logging:
  level:
    com.vankeytech.pmp.common.mapper: debug

#测试环境
---
spring:
  profiles: test
dubbo:
  debug:
  register: true
  registry: 192.168.0.100:2181,192.168.0.101:2181